
// This file was auto-generated by ML.NET Model Builder. 

using Road_temperatur_IoT_model_consoleApp;

// Create single instance of sample data from first line of dataset for model input
IoTModel.ModelInput sampleData = new IoTModel.ModelInput()
{
    NetworkId = @"E067-6EB9-0614-9339",
    AirTemperature = 246F,
    AirHumidity = 860F,
    Precipitation = 0F,
    BatteryLevel = 503F,
    Rssi = -750F,
    SeqNumber = 20F,
    TransmissionSeqNumber = 20F,
    FirmwareVersion = @"v2.5",
    Time = @"2023-12-25 20:05:34.000",
    CreatedAt = @"2023-12-25 20:08:41.772",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual RoadTemperature with predicted RoadTemperature from sample data...\n\n");


Console.WriteLine($"NetworkId: {@"E067-6EB9-0614-9339"}");
Console.WriteLine($"RoadTemperature: {93F}");
Console.WriteLine($"AirTemperature: {246F}");
Console.WriteLine($"AirHumidity: {860F}");
Console.WriteLine($"Precipitation: {0F}");
Console.WriteLine($"BatteryLevel: {503F}");
Console.WriteLine($"Rssi: {-750F}");
Console.WriteLine($"SeqNumber: {20F}");
Console.WriteLine($"TransmissionSeqNumber: {20F}");
Console.WriteLine($"FirmwareVersion: {@"v2.5"}");
Console.WriteLine($"Time: {@"2023-12-25 20:05:34.000"}");
Console.WriteLine($"CreatedAt: {@"2023-12-25 20:08:41.772"}");


var predictionResult = IoTModel.Predict(sampleData);
Console.WriteLine($"\n\nPredicted RoadTemperature: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

