// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;
using WeatherStationWRSenseMLModel_Api;

// Configure app
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddPredictionEnginePool<WeatherStationWRSenseMLMode.ModelInput, WeatherStationWRSenseMLMode.ModelOutput>()
    .FromFile("MLModel.mlnet");

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});
var app = builder.Build();

app.UseSwagger();

app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
});

// Define prediction route & handler
app.MapPost("/predict",
    async (PredictionEnginePool<WeatherStationWRSenseMLMode.ModelInput, WeatherStationWRSenseMLMode.ModelOutput> predictionEnginePool, WeatherStationWRSenseMLMode.ModelInput input) =>
        await Task.FromResult(predictionEnginePool.Predict(input)));


// Run app
app.Run();
